apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-postgres-3

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  selector:
    matchLabels:
      app: local-pv 